if(NOT DEFINED ENV{CONDA_PREFIX} OR "$ENV{CONDA_PREFIX}" STREQUAL "")
  message(FATAL_ERROR "A Conda environment must be active before configuring OpenSai.")
endif()

set(OPENSAI_CONDA_PREFIX "$ENV{CONDA_PREFIX}")

list(PREPEND CMAKE_PREFIX_PATH "${OPENSAI_CONDA_PREFIX}")
list(PREPEND CMAKE_FIND_ROOT_PATH "${OPENSAI_CONDA_PREFIX}")

set(CMAKE_FIND_USE_PACKAGE_REGISTRY FALSE CACHE BOOL "" FORCE)
set(CMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY TRUE CACHE BOOL "" FORCE)
set(CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY FALSE CACHE BOOL "" FORCE)
set(CMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY TRUE CACHE BOOL "" FORCE)
set(CMAKE_EXPORT_NO_PACKAGE_REGISTRY ON CACHE BOOL "" FORCE)

set(CMAKE_INCLUDE_PATH
    "${OPENSAI_CONDA_PREFIX}/include;${OPENSAI_CONDA_PREFIX}/include/eigen3;${CMAKE_INCLUDE_PATH}"
    CACHE STRING "" FORCE)
set(CMAKE_LIBRARY_PATH
    "${OPENSAI_CONDA_PREFIX}/lib;${CMAKE_LIBRARY_PATH}"
    CACHE STRING "" FORCE)
set(CMAKE_PROGRAM_PATH
    "${OPENSAI_CONDA_PREFIX}/bin;${CMAKE_PROGRAM_PATH}"
    CACHE STRING "" FORCE)

if(EXISTS "${OPENSAI_CONDA_PREFIX}/share/eigen3/cmake")
  set(Eigen3_DIR "${OPENSAI_CONDA_PREFIX}/share/eigen3/cmake" CACHE PATH "" FORCE)
endif()

if(EXISTS "${OPENSAI_CONDA_PREFIX}/lib/cmake/Eigen3")
  set(Eigen3_DIR "${OPENSAI_CONDA_PREFIX}/lib/cmake/Eigen3" CACHE PATH "" FORCE)
endif()

set(EIGEN3_INCLUDE_DIR "${OPENSAI_CONDA_PREFIX}/include/eigen3" CACHE PATH "" FORCE)
set(EIGEN3_INCLUDE_DIRS "${OPENSAI_CONDA_PREFIX}/include/eigen3" CACHE PATH "" FORCE)
